# Generated by Django 3.2.16 on 2024-07-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_post_comment_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object',
            new_name='post_object',
        ),
    ]
