# Generated by Django 3.2.16 on 2024-07-01 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_post_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.post'),
        ),
    ]
